# Generated by Django 5.2.17 on 2026-09-06 12:25

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_login_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authorization_version',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name='GatewayRevocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=64)),
                ('include_visitors', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subject', 'version'), name='unique_gateway_revocation')],
            },
        ),
    ]
