# Generated by Codex on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatgpt", "0005_chatgptaccount_auth_diagnostics"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatgptaccount",
            name="extra_cookies",
            field=models.JSONField(blank=True, default=list, verbose_name="额外 Cookie"),
        ),
    ]
