# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatgpt", "0007_chatgptaccount_proxy_node_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatgptaccount",
            name="refresh_client_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
